name: solve_ai
description: "An AI study assistant toolbox app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  firebase_core: ^3.8.1
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  get_it: ^8.0.3
  shared_preferences: ^2.3.3
  auto_route: ^9.2.2
  intl: ^0.19.0
  flutter_animate: ^4.5.2
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  logging: ^1.3.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  cross_file: ^0.3.4+2
  mime: ^2.0.0
  firebase_vertexai: ^1.0.4
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0

flutter_gen:
  output: lib/src/shared/assets/
  line_length: 80

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter_native_splash:
  color: "#EA5B29"
  image: assets/images/splash.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: NewYork
      fonts:
        - asset: assets/fonts/NewYork.ttf
    - family: SanFransisco
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
